apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubetest
spec:
  selector:
    matchLabels:
      app: kubetest
  template:
    metadata:
      labels:
        app: kubetest
    spec:
      containers:
      - name: kubetest
        image: localhost:32000/kubetest:v1.0.0
        ports:
        - containerPort: 5000
        imagePullPolicy: Always
        volumeMounts:
          - mountPath: /app
            name: kubetest-volume
            readOnly: true
      volumes:
      - name: kubetest-volume
        hostPath:
          path: /home/noah/kubetest
          type: Directory
---
kind: Service
apiVersion: v1
metadata:
  name: kubetest
  labels:
    app: kubetest
spec:
  selector:
    app: kubetest
  ports:
  - name: http
    port: 5000
    protocol: TCP
  type: NodePort